Repository Pelter-Team/Pelter-Backend, pull requests merged in 2024-11, with the labels that each got.

#9 [SHEL-80] User Role Based Validation and Product routes
  .air.toml
  docker-compose.yml
  internal/dto/product.go
  internal/entity/product.go
  internal/middleware/validate.go
  internal/pkg/jwt/jwt.go
  internal/product/product.repository.go
  internal/product/product.route.go
  internal/product/product.service.go
  internal/product/product.usecase.go
Labels: Ready to Review

#8 [SHEL-84]-Transaction-Route
  Makefile
  docker-compose.yml
  internal/dto/transaction.go
  internal/entity/transaction.go
  internal/server/server.go
  internal/transaction/transaction.repository.go
  internal/transaction/transaction.route.go
  internal/transaction/transaction.service.go
  internal/transaction/transaction.usecase.go
  internal/user/user.repository.go
Labels: enhancement, Ready to Review

#10 [SHEL-98] Admin Routes for Product
  internal/product/product.repository.go
  internal/product/product.route.go
  internal/product/product.service.go
  internal/product/product.usecase.go
  internal/utils/converter.go
Labels: Ready to Review

#15 [SHEL-105] User ID equal 0 in get products
  Makefile
  docker-compose.yml
  internal/entity/product.go
Labels: Ready to Review

#13 SHEL-102-Cannot-Create-Account-as-Admin
  internal/entity/user.go
  internal/user/user.service.go
Labels: fix
